### ISSUE TITLE
Topics Pages links broken

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#100]

**Comment by markmcdonald51** [comment]
Ok. Fix the pages. This is going to need some design work. And I need to know exactly what the Sicomines link does and it's really clear what is happening in this code. Not closing this, commenting for now.

**Comment by charleshuang80** [comment]
@markmcdonald51 copying in the same comment I made in https://github.com/crowdcover/congo-mines-app/issues/24, which should fix the link for Sicomines page.
"@markmcdonald51 Can you please change the setup for the pages setup, so that the page with topic Sicomines has category_id: nil, drc_company_id: 74
This is needed for it to render properly. The most recent database doesn't have this set up properly."
