### ISSUE TITLE
Fix search to handle accented characters

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#94]
Can we make search flexible enough to handle accented characters.  E.g.
* Gecamines should return the same results as Gécamines

**Comment by charleshuang80** [comment]
@markmcdonald51 I figured out how to make this work, but since we are .gitignoring all the solr files, I think you will need to add something to the solr/schema.xml file.
In schema.xml, we need to add a solr.ASCIIFoldingFilterFactory for how solr treats TextFields. I copied the section below, but we only need to add that one line:

    <fieldType name="text" class="solr.TextField" omitNorms="false">
      <analyzer>
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.StandardFilterFactory"/>
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.PorterStemFilterFactory"/>
        <filter class="solr.ASCIIFoldingFilterFactory"/> 
      </analyzer>
    </fieldType>

I found the solution in these links (for reference)
http://www.bitabit.eng.br/2011/03/16/sunspot-solr-how-to-sort-accented-fields/
http://stackoverflow.com/questions/22072050/ignore-accents-in-solr-and-sunspot

I think it would be wise to reindex after making the change as well.
